---
- name: "Download Filebeat's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-x86_64.rpm"
    dest: "/tmp/filebeat-{{ filebeat_version }}-x86_64.rpm"
    mode: 0740
  register: download_filebeat
  until: download_filebeat is succeeded
